##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

server {
	listen   80; ## listen for ipv4
	listen   [::]:80; ## listen for ipv6

	listen   443 ssl; ## listen for ipv4
	listen   [::]:443 ssl; ## listen for ipv6

	ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
	ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

	server_name paste.example.com;

	root /usr/share/nginx/sites/paste.example.com;
	index index.php index.html index.htm;

	autoindex off;

	location / {
		try_files $uri $uri/ =404;
	}

	location ~ "^/([a-zA-Z0-9]{16}(@raw)?)$" {
		try_files $uri $uri/ /index.php?p=$1;
	}

	# change this to match your database
	# 
	location = /00112233445566778899aabbccddeeff.sqlite {
		deny all;
	}

	# pass PHP scripts to FastCGI server
	#
	location ~ \.php$ {
		include snippets/fastcgi-php.conf;

		# With php-fpm (or other unix sockets):
		fastcgi_pass unix:/run/php/php8.2-fpm.sock;
		# With php-cgi (or other tcp sockets):
		# fastcgi_pass 127.0.0.1:9000;
	}
}
